### ISSUE TITLE
Update dialog should be pre-populated with title and description

### ISSUE THREAD

**Issue by mosaicbytes** [Abhishek-Dobliyal/To-Do#1]
The update dialog should display the title and description of the item selected for editing.  Right now, the user really has no way of knowing if the item they are updating is the item they WANT to update.  The user may intend to update the first item in the list but accidentally click to update the second  item in the list.  If they submit the update, this results in overwriting the wrong item in the list.

**Comment by Abhishek-Dobliyal** [comment]
Thanks for looking into this. Really appreciate your observation.
